version: '3'

services:
  myservice:
    image: jbuild
    # # Optional
    # env_file:
    #   - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NB_UID=${NB_UID}
        - NB_GID=${NB_GID}
    entrypoint: sh -c "sleep infinity"